import { t } from "elysia";

export const ProvinceEnum = t.Union([
	t.Literal("TP. Hà Nội"),
	t.Literal("Cao Bằng"),
	t.Literal("Tuyên Quang"),
	t.Literal("Lào Cai"),
	t.Literal("Điện Biên"),
	t.Literal("Lai Châu"),
	t.Literal("Sơn La"),
	t.Literal("Thái Nguyên"),
	t.Literal("Lạng Sơn"),
	t.Literal("Quảng Ninh"),
	t.Literal("Phú Thọ"),
	t.Literal("Bắc Ninh"),
	t.Literal("TP. Hải Phòng"),
	t.Literal("Hưng Yên"),
	t.Literal("Ninh Bình"),
	t.Literal("Thanh Hoá"),
	t.Literal("Nghệ An"),
	t.Literal("Hà Tĩnh"),
	t.Literal("Quảng Trị"),
	t.Literal("TP. Huế"),
	t.Literal("TP. Đà Nẵng"),
	t.Literal("Quảng Ngãi"),
	t.Literal("Khánh Hoà"),
	t.Literal("Gia Lai"),
	t.Literal("Đắk Lắk"),
	t.Literal("Lâm Đồng"),
	t.Literal("Tây Ninh"),
	t.Literal("Đồng Nai"),
	t.Literal("TP. Hồ Chí Minh"),
	t.Literal("Vĩnh Long"),
	t.Literal("Đồng Tháp"),
	t.Literal("An Giang"),
	t.Literal("TP. Cần Thơ"),
	t.Literal("Cà Mau"),
]);
