create extension if not exists "pg_cron" with schema "pg_catalog";

create type "public"."Demon difficulty" as enum ('Easy Demon', 'Medium Demon', 'Hard Demon', 'Insane Demon', 'Extreme Demon');

create type "public"."Provinces" as enum ('TP. Hà Nội', 'Cao Bằng', 'Tuyên Quang', 'Lào Cai', 'Điện Biên', 'Lai Châu', 'Sơn La', 'Thái Nguyên', 'Lạng Sơn', 'Quảng Ninh', 'Phú Thọ', 'Bắc Ninh', 'TP. Hải Phòng', 'Hưng Yên', 'Ninh Bình', 'Thanh Hoá', 'Nghệ An', 'Hà Tĩnh', 'Quảng Trị', 'TP. Huế', 'TP. Đà Nẵng', 'Quảng Ngãi', 'Khánh Hoà', 'Gia Lai', 'Đắk Lắk', 'Lâm Đồng', 'Tây Ninh', 'Đồng Nai', 'TP. Hồ Chí Minh', 'Vĩnh Long', 'Đồng Tháp', 'An Giang', 'TP. Cần Thơ', 'Cà Mau');


  create table "public"."creators" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "email" text,
    "facebook" text,
    "youtube" text,
    "discord" text,
    "gdbrowser" text,
    "total_cp_point" bigint,
    "cp_rated_point" bigint,
    "cp_featured_point" bigint,
    "cp_epic_point" bigint,
    "cp_legendary_point" bigint,
    "cp_mythic_point" bigint,
    "uid" uuid not null default extensions.uuid_generate_v4(),
    "overall_rank" bigint,
    "province" public."Provinces",
    "gd_username" text not null
      );


alter table "public"."creators" enable row level security;


  create table "public"."levels" (
    "id" bigint generated by default as identity not null,
    "name" character varying not null default 'N/A'::character varying,
    "creator_gd_username" text default 'N/A'::character varying,
    "video_id" character varying default 'N/A'::character varying,
    "difficulty_star_number" bigint not null,
    "is_demon" boolean not null default false,
    "demon_difficulty" public."Demon difficulty",
    "rated_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "ingame_level_id" bigint not null
      );


alter table "public"."levels" enable row level security;


  create table "public"."mappack_levels" (
    "mappack_id" bigint not null,
    "level_id" bigint not null,
    "position" integer not null
      );


alter table "public"."mappack_levels" enable row level security;


  create table "public"."mappacks" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "name" text not null,
    "color_primary" text,
    "color_secondary" text,
    "description" text,
    "is_gradient" boolean not null default false,
    "gradient_color_1" text,
    "gradient_color_2" text,
    "gradient_color_3" text
      );


alter table "public"."mappacks" enable row level security;

CREATE UNIQUE INDEX creators_pkey ON public.creators USING btree (gd_username);

CREATE UNIQUE INDEX levels_level_id_key ON public.levels USING btree (ingame_level_id);

CREATE UNIQUE INDEX levels_pkey ON public.levels USING btree (id);

CREATE UNIQUE INDEX mappack_levels_pkey ON public.mappack_levels USING btree (mappack_id, level_id);

CREATE UNIQUE INDEX mappacks_pkey ON public.mappacks USING btree (id);

alter table "public"."creators" add constraint "creators_pkey" PRIMARY KEY using index "creators_pkey";

alter table "public"."levels" add constraint "levels_pkey" PRIMARY KEY using index "levels_pkey";

alter table "public"."mappack_levels" add constraint "mappack_levels_pkey" PRIMARY KEY using index "mappack_levels_pkey";

alter table "public"."mappacks" add constraint "mappacks_pkey" PRIMARY KEY using index "mappacks_pkey";

alter table "public"."levels" add constraint "levels_creator_fkey" FOREIGN KEY (creator_gd_username) REFERENCES public.creators(gd_username) not valid;

alter table "public"."levels" validate constraint "levels_creator_fkey";

alter table "public"."levels" add constraint "levels_level_id_key" UNIQUE using index "levels_level_id_key";

alter table "public"."mappack_levels" add constraint "mappack_levels_level_id_fkey" FOREIGN KEY (level_id) REFERENCES public.levels(id) ON DELETE CASCADE not valid;

alter table "public"."mappack_levels" validate constraint "mappack_levels_level_id_fkey";

alter table "public"."mappack_levels" add constraint "mappack_levels_mappack_id_fkey" FOREIGN KEY (mappack_id) REFERENCES public.mappacks(id) ON DELETE CASCADE not valid;

alter table "public"."mappack_levels" validate constraint "mappack_levels_mappack_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.add_event_levels_progress(updates jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  item jsonb;
BEGIN
  FOR item IN SELECT * FROM jsonb_array_elements(updates)
  LOOP
    UPDATE "eventLevels"
    SET "totalProgress" = "totalProgress" + (item->>'gained')::float
    WHERE "id" = (item->>'level_id')::int;
  END LOOP;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_event_leaderboard(event_id integer)
 RETURNS TABLE("userID" uuid, elo bigint, "matchCount" bigint, point numeric, penalty numeric)
 LANGUAGE plpgsql
AS $function$BEGIN
  RETURN QUERY
  SELECT
    er."userID",
    p.elo,
    p."matchCount",
    COALESCE(SUM((er.progress::numeric * el.point::numeric) / 100), 0) AS point,
    SUM(
      EXTRACT(EPOCH FROM (er.created_at - e.start)) / 60
    ) AS penalty
  FROM
    "eventRecords" AS er
    JOIN "eventLevels" AS el ON er."levelID" = el.id
    JOIN events AS e ON e.id = el."eventID"
    JOIN players AS p ON p.uid = er."userID"
  WHERE
    el."eventID" = event_id
  GROUP BY
    er."userID",
    p."elo",
    p."matchCount"
  ORDER BY
    point DESC,
    penalty ASC;
END;$function$
;

CREATE OR REPLACE FUNCTION public.get_top_buyers(interval_ms bigint, limit_count integer, offset_count integer)
 RETURNS TABLE(uid uuid, "totalAmount" double precision)
 LANGUAGE plpgsql
 STABLE
AS $function$
BEGIN
  RETURN QUERY
  SELECT 
    p.uid,
    SUM(o.amount) AS "totalAmount"
  FROM orders o
  JOIN players p ON p.uid = o."userID"
  WHERE o.created_at >= NOW() - (interval '1 millisecond' * interval_ms)
    AND p.uid != '3e788ac1-989c-4d2b-bfaf-f99059d258cf'
  GROUP BY p.uid
  ORDER BY "totalAmount" DESC
  LIMIT limit_count
  OFFSET offset_count;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.update_list()
 RETURNS void
 LANGUAGE plpgsql
AS $function$begin
WITH
  v_table_name AS (
    SELECT
      id,
      (
        case
          when "flTop" is not null then RANK() OVER (
            ORDER BY
              "flTop" asc nulls last
          )
        end
      ) as ab
    FROM
      levels
  )
UPDATE
  levels
set
  "flTop" = v_table_name.ab
FROM
  v_table_name
WHERE
  levels.id = v_table_name.id;

WITH
  v_table_name AS (
    SELECT
      id,
      "isPlatformer",
      (
        case
          when "rating" is not null then RANK() OVER (
            ORDER BY
              "rating" desc nulls last
          )
        end
      ) as ab
    FROM
      levels
    where "isPlatformer" = false
  )
UPDATE
  levels
set
  "dlTop" = v_table_name.ab
FROM
  v_table_name
WHERE
  levels.id = v_table_name.id;

WITH
  v_table_name AS (
    SELECT
      id,
      "isPlatformer",
      (
        case
          when "rating" is not null then RANK() OVER (
            ORDER BY
              "rating" desc nulls last
          )
        end
      ) as ab
    FROM
      levels
    where "isPlatformer" = true
  )
UPDATE
  levels
set
  "dlTop" = v_table_name.ab
FROM
  v_table_name
WHERE
  levels.id = v_table_name.id;

UPDATE
  levels
SET
  "flPt" = cast(
    2250 / (0.4 * ("flTop") + 7) - 55 as decimal(16, 2)
  )
where
  "flTop" < 76;

UPDATE
  levels
SET
  "flPt" = 1
where
  "flTop" > 75;

update clans
set "memberCount" = (select count(*) from players where players.clan = clans.id)
where true;

update levels set "flPt" = null where "flTop" is null;
update levels set "dlTop" = null where "rating" is null;
end$function$
;

CREATE OR REPLACE FUNCTION public.update_rank()
 RETURNS void
 LANGUAGE plpgsql
AS $function$begin
update players
set
  "isHidden" = true
where
  "isBanned" = true;

with
  v_table_a as (
    select
      records.userid,
      records.levelid,
      records."dlPt",
      levels.rating,
      rank() over (
        partition by
          userid
        order by
          case
            when records."isChecked" = false then null
            when records.progress = 100 then levels.rating
            else levels.rating * records.progress / 150
          end desc nulls last,
          levels.name
      ) as no
    from
      records,
      levels
    where
      levels.id = records.levelid
      and levels."isPlatformer" = false
  )
update records
set
  no = v_table_a.no
from
  v_table_a
where
  records.userid = v_table_a.userid
  and records.levelid = v_table_a.levelid
  and v_table_a.rating is not null;

update records
set
  "flPt" = cast(
    (
      select
        "flPt"
      from
        levels
      where
        levels.id = records.levelid
    ) as decimal(16, 2)
  )
where
  progress = 100;

with
  v_b as (
    select
      records.userid,
      records.levelid,
      case
        when records.no is null then null
        when records.no = 1 then levels.rating * 5 / 10
        when records.no = 2 then levels.rating * 3 / 10
        when records.no = 3 then levels.rating * 2 / 10
        when (
          records.no > 3
          and records.no <= 15
        ) then greatest(
          5,
          floor(levels.rating * (25.0 / records.no) / 100)
        )
        when (
          records.no > 15
          and records.no <= 25
        ) then 5
        else 1
      end as pt
    from
      records,
      levels
    where
      levels.id = records.levelid
      and levels."isPlatformer" = false
  )
update records
set
  "dlPt" = v_b.pt
from
  v_b
where
  records.userid = v_b.userid
  and records.levelid = v_b.levelid
  and records.progress = 100;

with
  v_b as (
    select
      records.userid,
      records.levelid,
      case
        when records.no is null then null
        when records.no = 1 then levels.rating * 5 / 10
        when records.no = 2 then levels.rating * 3 / 10
        when records.no = 3 then levels.rating * 2 / 10
        when (
          records.no > 1
          and records.no <= 15
        ) then greatest(
          5,
          floor(levels.rating * (25.0 / records.no) / 100)
        )
        when (
          records.no > 15
          and records.no <= 25
        ) then 5
        else 1
      end as pt
    from
      records,
      levels
    where
      levels.id = records.levelid
      and levels."isPlatformer" = false
  )
update records
set
  "dlPt" = v_b.pt * progress / 150
from
  v_b
where
  records.userid = v_b.userid
  and records.levelid = v_b.levelid
  and records.progress < 100;

update players
set
  "totalFLpt" = (
    select
      sum("flPt")
    from
      records
    where
      records.userid = players.uid
      and records."isChecked" = true
  )
where
  true;

update players
set
  "totalDLpt" = (
    select
      sum("dlPt")
    from
      records
    where
      records.userid = players.uid
      and records."isChecked" = true
  )
where
  true;

update players
set
  "dlMaxPt" = greatest(
    (
      select
        max("dlPt")
      from
        records
      where
        records.userid = players.uid
        and records."isChecked" = true
    ),
    -1
  )
where
  true;

update players
set
  "flMaxPt" = greatest(
    (
      select
        max("flPt")
      from
        records
      where
        records.userid = players.uid
        and records."isChecked" = true
    ),
    -1
  )
where
  true;

update players
set
  rating = cast(
    (
      select
        sum("dlPt")
      from
        records
      where
        records.userid = players.uid
        and records."isChecked" = true
    ) as integer
  )
where
  true;

update players
set
  rating = null
where
  "isHidden";

with
  v_table_name as (
    select
      uid,
      (
        case
          when "totalFLpt" is not null then RANK() over (
            order by
              "totalFLpt" desc nulls last
          )
        end
      ) as ab
    from
      players
  )
update players
set
  "flrank" = v_table_name.ab
from
  v_table_name
where
  players.uid = v_table_name.uid;

with
  v_table_name as (
    select
      uid,
      (
        case
          when "totalDLpt" is not null then RANK() over (
            order by
              "totalDLpt" desc nulls last
          )
        end
      ) as ab
    from
      players
  )
update players
set
  "dlrank" = v_table_name.ab
from
  v_table_name
where
  players.uid = v_table_name.uid;

with
  v_table_name as (
    select
      uid,
      (
        case
          when "rating" is not null
          and "rating" != 0 then RANK() over (
            order by
              "rating" desc nulls last
          )
        end
      ) as ab
    from
      players
  )
update players
set
  "overallRank" = v_table_name.ab
from
  v_table_name
where
  players.uid = v_table_name.uid;

with
  v_table_a as (
    select
      userid,
      count(*)
    from
      records
    where
      "isChecked" = true
    group by
      userid
  )
update players
set
  "recordCount" = v_table_a.count
from
  v_table_a
where
  players.uid = v_table_a.userid;

with
  v_table_a as (
    select
      records.userid,
      coalesce(sum(levels.rating), 0) as sum,
      count(*)
    from
      records,
      levels
    where
      levels.id = records.levelid
      and records."isChecked" = true
    group by
      records.userid
  )
update players
set
  exp = v_table_a.count * 50 + v_table_a.sum
from
  v_table_a
where
  uid = v_table_a.userid;

update players
set
  "extraExp" = 0
where
  true;

with
  v_table_a as (
    select
      "eventProofs".userid,
      sum(events.exp)
    from
      events,
      "eventProofs"
    where
      events.id = "eventProofs"."eventID"
      and "eventProofs".accepted = true
    group by
      "eventProofs".userid
  )
update players
set
  "extraExp" = v_table_a.sum
from
  v_table_a
where
  players.uid = v_table_a.userid;

update records
set
  "queueNo" = null
where
  true;

with
  RankedRecords as (
    select
      ROW_NUMBER() over (
        order by
          case
            when p."supporterUntil" is null then r.timestamp
            when p."supporterUntil" > NOW() then (r.timestamp - 2592000000)::int8
            else r.timestamp
          end
      ) as "queueNo",
      r.userid,
      r.levelid,
      r."isChecked",
      r."needMod",
      r."reviewer",
      p."supporterUntil"
    from
      public.records r
      join public.players p on r.userid = p.uid
    where
      r."isChecked" = false
      and r."needMod" = false
      and r."reviewer" is null
  )
update records
set
  "queueNo" = RankedRecords."queueNo"
from
  RankedRecords
where
  records.userid = RankedRecords.userid
  and records.levelid = RankedRecords.levelid;

update public.records r
set
  "plPt" = sub."plPt"
from
  (
    select
      r.userid,
      r.levelid,
      case
        when r.progress <= 0
        or l."minProgress" is null
        or l."minProgress" <= 0 then 0
        else GREATEST(
          0.3 * COALESCE(l.rating, 0),
          COALESCE(l.rating, 0) * POWER(
            l."minProgress"::double precision / r.progress,
            0.5849625
          )
        )
      end as "plPt"
    from
      public.records r
      join public.levels l on l.id = r.levelid
    where
      r."isChecked" = true
      and l."isPlatformer" = true
  ) as sub
where
  r.userid = sub.userid
  and r.levelid = sub.levelid;

with
  ranked_plays as (
    select
      r.userid,
      r.levelid,
      r."plPt",
      ROW_NUMBER() over (
        partition by
          r.userid
        order by
          r."plPt" desc
      ) as rn
    from
      public.records r
      join public.levels l on l.id = r.levelid
    where
      r."isChecked" = true
      and l."isPlatformer" = true
  ),
  weighted as (
    select
      userid,
      "plPt",
      rn,
      case
        when rn = 1 then 0.5
        when rn = 2 then 0.3
        when rn = 3 then 0.15
        else GREATEST(0.01, 0.05 / POWER(rn - 3, 0.5))
      end as weight
    from
      ranked_plays
  ),
  sum_weighted as (
    select
      userid,
      SUM("plPt" * weight) as total_rating
    from
      weighted
    group by
      userid
  )
update public.players p
set
  "plRating" = case
    when sw.total_rating = 0 then null
    else sw.total_rating
  end
from
  sum_weighted sw
where
  p.uid = sw.userid;

with
  ranked_players as (
    select
      uid,
      RANK() over (
        order by
          "plRating" desc nulls last
      ) as rnk
    from
      public.players
  )
update public.players p
set
  "plrank" = rp.rnk
from
  ranked_players rp
where
  p.uid = rp.uid;
end$function$
;

CREATE OR REPLACE FUNCTION public.update_supporter_until()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
    user_record RECORD;
    order_record RECORD;
    current_supporter_until TIMESTAMP;
BEGIN
    -- Lặp qua từng user có đơn hàng
    FOR user_record IN 
        SELECT DISTINCT COALESCE("giftTo", "userID") as target_uid
        FROM orders 
        WHERE "productID" = 1 AND delivered = true
    LOOP
        current_supporter_until := NULL;
        
        -- Xử lý từng đơn hàng theo thứ tự thời gian
        FOR order_record IN 
            SELECT created_at, quantity
            FROM orders 
            WHERE "productID" = 1 AND delivered = true
            AND COALESCE("giftTo", "userID") = user_record.target_uid
            ORDER BY created_at
        LOOP
            IF current_supporter_until IS NULL OR current_supporter_until < order_record.created_at THEN
                -- Nếu chưa có hoặc đã hết hạn supporter
                current_supporter_until := order_record.created_at + INTERVAL '1 month' * order_record.quantity;
            ELSE
                -- Nếu vẫn còn supporter, cộng thêm thời gian
                current_supporter_until := current_supporter_until + INTERVAL '1 month' * order_record.quantity;
            END IF;
        END LOOP;
        
        -- Cập nhật vào database
        UPDATE players 
        SET "supporterUntil" = current_supporter_until
        WHERE uid = user_record.target_uid;
    END LOOP;
END;
$function$
;

grant delete on table "public"."creators" to "anon";

grant insert on table "public"."creators" to "anon";

grant references on table "public"."creators" to "anon";

grant select on table "public"."creators" to "anon";

grant trigger on table "public"."creators" to "anon";

grant truncate on table "public"."creators" to "anon";

grant update on table "public"."creators" to "anon";

grant delete on table "public"."creators" to "authenticated";

grant insert on table "public"."creators" to "authenticated";

grant references on table "public"."creators" to "authenticated";

grant select on table "public"."creators" to "authenticated";

grant trigger on table "public"."creators" to "authenticated";

grant truncate on table "public"."creators" to "authenticated";

grant update on table "public"."creators" to "authenticated";

grant delete on table "public"."creators" to "postgres";

grant insert on table "public"."creators" to "postgres";

grant references on table "public"."creators" to "postgres";

grant select on table "public"."creators" to "postgres";

grant trigger on table "public"."creators" to "postgres";

grant truncate on table "public"."creators" to "postgres";

grant update on table "public"."creators" to "postgres";

grant delete on table "public"."creators" to "service_role";

grant insert on table "public"."creators" to "service_role";

grant references on table "public"."creators" to "service_role";

grant select on table "public"."creators" to "service_role";

grant trigger on table "public"."creators" to "service_role";

grant truncate on table "public"."creators" to "service_role";

grant update on table "public"."creators" to "service_role";

grant delete on table "public"."levels" to "anon";

grant insert on table "public"."levels" to "anon";

grant references on table "public"."levels" to "anon";

grant select on table "public"."levels" to "anon";

grant trigger on table "public"."levels" to "anon";

grant truncate on table "public"."levels" to "anon";

grant update on table "public"."levels" to "anon";

grant delete on table "public"."levels" to "authenticated";

grant insert on table "public"."levels" to "authenticated";

grant references on table "public"."levels" to "authenticated";

grant select on table "public"."levels" to "authenticated";

grant trigger on table "public"."levels" to "authenticated";

grant truncate on table "public"."levels" to "authenticated";

grant update on table "public"."levels" to "authenticated";

grant delete on table "public"."levels" to "postgres";

grant insert on table "public"."levels" to "postgres";

grant references on table "public"."levels" to "postgres";

grant select on table "public"."levels" to "postgres";

grant trigger on table "public"."levels" to "postgres";

grant truncate on table "public"."levels" to "postgres";

grant update on table "public"."levels" to "postgres";

grant delete on table "public"."levels" to "service_role";

grant insert on table "public"."levels" to "service_role";

grant references on table "public"."levels" to "service_role";

grant select on table "public"."levels" to "service_role";

grant trigger on table "public"."levels" to "service_role";

grant truncate on table "public"."levels" to "service_role";

grant update on table "public"."levels" to "service_role";

grant delete on table "public"."mappack_levels" to "anon";

grant insert on table "public"."mappack_levels" to "anon";

grant references on table "public"."mappack_levels" to "anon";

grant select on table "public"."mappack_levels" to "anon";

grant trigger on table "public"."mappack_levels" to "anon";

grant truncate on table "public"."mappack_levels" to "anon";

grant update on table "public"."mappack_levels" to "anon";

grant delete on table "public"."mappack_levels" to "authenticated";

grant insert on table "public"."mappack_levels" to "authenticated";

grant references on table "public"."mappack_levels" to "authenticated";

grant select on table "public"."mappack_levels" to "authenticated";

grant trigger on table "public"."mappack_levels" to "authenticated";

grant truncate on table "public"."mappack_levels" to "authenticated";

grant update on table "public"."mappack_levels" to "authenticated";

grant delete on table "public"."mappack_levels" to "postgres";

grant insert on table "public"."mappack_levels" to "postgres";

grant references on table "public"."mappack_levels" to "postgres";

grant select on table "public"."mappack_levels" to "postgres";

grant trigger on table "public"."mappack_levels" to "postgres";

grant truncate on table "public"."mappack_levels" to "postgres";

grant update on table "public"."mappack_levels" to "postgres";

grant delete on table "public"."mappack_levels" to "service_role";

grant insert on table "public"."mappack_levels" to "service_role";

grant references on table "public"."mappack_levels" to "service_role";

grant select on table "public"."mappack_levels" to "service_role";

grant trigger on table "public"."mappack_levels" to "service_role";

grant truncate on table "public"."mappack_levels" to "service_role";

grant update on table "public"."mappack_levels" to "service_role";

grant delete on table "public"."mappacks" to "anon";

grant insert on table "public"."mappacks" to "anon";

grant references on table "public"."mappacks" to "anon";

grant select on table "public"."mappacks" to "anon";

grant trigger on table "public"."mappacks" to "anon";

grant truncate on table "public"."mappacks" to "anon";

grant update on table "public"."mappacks" to "anon";

grant delete on table "public"."mappacks" to "authenticated";

grant insert on table "public"."mappacks" to "authenticated";

grant references on table "public"."mappacks" to "authenticated";

grant select on table "public"."mappacks" to "authenticated";

grant trigger on table "public"."mappacks" to "authenticated";

grant truncate on table "public"."mappacks" to "authenticated";

grant update on table "public"."mappacks" to "authenticated";

grant delete on table "public"."mappacks" to "postgres";

grant insert on table "public"."mappacks" to "postgres";

grant references on table "public"."mappacks" to "postgres";

grant select on table "public"."mappacks" to "postgres";

grant trigger on table "public"."mappacks" to "postgres";

grant truncate on table "public"."mappacks" to "postgres";

grant update on table "public"."mappacks" to "postgres";

grant delete on table "public"."mappacks" to "service_role";

grant insert on table "public"."mappacks" to "service_role";

grant references on table "public"."mappacks" to "service_role";

grant select on table "public"."mappacks" to "service_role";

grant trigger on table "public"."mappacks" to "service_role";

grant truncate on table "public"."mappacks" to "service_role";

grant update on table "public"."mappacks" to "service_role";


  create policy "Enable read access for all users"
  on "public"."creators"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."levels"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."mappack_levels"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."mappacks"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "storage"."buckets"
  as permissive
  for insert
  to public
with check (true);



